"""initial_migration

Revision ID: 0001_initial
Revises: 
Create Date: 2024-05-23 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('rate_uzs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=False)
    op.create_index(op.f('ix_currencies_date'), 'currencies', ['date'], unique=False)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    
    op.create_table('tn_ved_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('full_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tn_ved_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tn_ved_codes_code'), 'tn_ved_codes', ['code'], unique=True)
    op.create_index(op.f('ix_tn_ved_codes_full_code'), 'tn_ved_codes', ['full_code'], unique=False)
    op.create_index(op.f('ix_tn_ved_codes_id'), 'tn_ved_codes', ['id'], unique=False)
    
    op.create_table('tariff_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tnved_id', sa.Integer(), nullable=False),
    sa.Column('import_duty_percent', sa.Float(), nullable=True),
    sa.Column('import_duty_specific', sa.Float(), nullable=True),
    sa.Column('specific_unit', sa.String(), nullable=True),
    sa.Column('excise_percent', sa.Float(), nullable=True),
    sa.Column('excise_specific', sa.Float(), nullable=True),
    sa.Column('vat_percent', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tnved_id'], ['tn_ved_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tnved_id')
    )
    op.create_index(op.f('ix_tariff_rates_id'), 'tariff_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_rates_id'), table_name='tariff_rates')
    op.drop_table('tariff_rates')
    op.drop_index(op.f('ix_tn_ved_codes_id'), table_name='tn_ved_codes')
    op.drop_index(op.f('ix_tn_ved_codes_full_code'), table_name='tn_ved_codes')
    op.drop_index(op.f('ix_tn_ved_codes_code'), table_name='tn_ved_codes')
    op.drop_table('tn_ved_codes')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_date'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
